---
apiVersion: v1
kind: Namespace
metadata:
  name: data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
  namespace: data
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ingest
  template:
    metadata:
      labels:
        app: ingest
    spec:
      containers:
        - envFrom:
          - secretRef:
              name: ingest-secrets
              optional: false
          name: ingest
          image: undpgeohub.azurecr.io/geohub-data-pipeline:main
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ingest-service
  namespace: data
spec:
  selector:
    app: ingest
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-servicebus-queue-scaledobject
  namespace: data
spec:
  scaleTargetRef:
    kind: Deployment
    name: ingest
  cooldownPeriod: 60 
  minReplicaCount:  1
  maxReplicaCount:  3 
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: data-upload
      namespace: undpgeohub
      messageCount: "5" # default 5
      activationMessageCount: "1"
      connectionFromEnv: SERVICE_BUS_CONNECTION_STRING

